static const char *g_shader_fragment_font = ""
#if defined(USE_LD)
"font.frag.glsl"
#else
"layout(location=5)uniform sampler2D A;"
"layout(location=7)uniform vec3 U;"
"layout(location=8)uniform vec3 L;"
"layout(location=9)uniform float T;"
"layout(location=10)uniform vec2 N[96];"
"in vec2 d;"
"out vec4 o;"
"void main()"
"{"
"float l=sqrt(sqrt(sqrt(sqrt(sqrt(1.-abs(T-.5)*2.))))),e=0;"
"for(int t=0;"
"t<96;"
"++t)"
"{"
"float o=1.-abs(N[t].s-d.t);"
"e=max(smoothstep(1.-(1.-l)*.5,1.,o),e);"
"}"
"float v=texture(A,d).s,c=max(v-e,.0);"
"vec3 a=mix(L*2.,U,c);"
"float f=B(a);"
"vec3 n=mix(vec3(1.-f),a,v);"
"o=vec4(n*c,c);"
"}"
#endif
"";
