static const char *g_shader_fragment_huygens_post = ""
#if defined(USE_LD)
"huygens_post.frag.glsl"
#else
"layout(location=0)uniform vec3 h[5];"
"layout(location=5)uniform sampler2D A;"
"layout(location=7)uniform sampler2D U;"
"layout(location=10)uniform vec2 L[96];"
"in vec2 t;"
"in vec2 d;"
"in vec2 e;"
"in vec2 n;"
"in vec2 s;"
"in vec2 u;"
"in vec2 m;"
"out vec4 o;"
"vec2 b(vec2 e,vec2 t)"
"{"
"float c=t.s*77.,o=c-.012,v=c+.012;"
"if(e.s>o&&e.s<v)"
"{"
"float c=(e.s-o)/(v-o),v=1.-(c*2.-1.),o=c*3.14159*5.;"
"return vec2(e.s,e.t+(sin(o)*t.t+sin(o+3.14159)*(1.-t.t))*v*.4);"
"}"
"return e;"
"}"
"void main()"
"{"
"vec2 c=e,v=n,a=s,l=u,f=m;"
"for(int t=0;"
"t<96;"
"++t)"
"{"
"vec2 e=L[t];"
"c=b(c,e),v=b(v,e),a=b(a,e),l=b(l,e),f=b(f,e);"
"}"
"vec4 n=W(A,t,c,v,a,l,f);"
"float u=B(n.stp),e=smoothstep(-2.,1.5,i(U,d.st*.00006+h[4].p*.5));"
"e*=e*e*e*e;"
"float r=h[4].p*777.+h[4].t*.02;"
"vec2 s=(mod(d*(sin((d.s+r)*.002)*.25+.75)*(cos((d.t-r)*.002)*.25+.75),12.)-6.)/6.;"
"e*=1.-dot(s,s),o=vec4(mix(n.stp,1.-n.stp,e),1.);"
"}"
#endif
"";
