static const char *g_shader_fragment_precalc = ""
#if defined(USE_LD)
"precalc.frag.glsl"
#else
"layout(location=0)uniform int m;"
"layout(location=5)uniform sampler2D u;"
"int A=1,U=2,L=3,T=4,N=5;"
"in vec2 e;"
"out vec4 o;"
"void main()"
"{"
"if(m==A)o=texture(u,e)*.5+.5;"
"else if(m==U)"
"{"
"float t=sqrt(texture(u,e).q);"
"o=vec4(vec3(t),1.);"
"}"
"else if(m==L)"
"{"
"float t=texture(u,e).p*4;"
"o=vec4(t,-t,.0,1.);"
"}"
"else if(m==T)"
"{"
"float t=texture(u,e).s;"
"o=vec4(t,-t,.0,1.);"
"}"
"else if(m==N)"
"{"
"float t=texture(u,e).t;"
"o=vec4(t,-t,.0,1.);"
"}"
"else o=texture(u,e);"
"}"
#endif
"";
