static const char *g_shader_fragment_space_post = ""
#if defined(USE_LD)
"space_post.frag.glsl"
#else
"layout(location=0)uniform vec3 d[5];"
"layout(location=5)uniform sampler2D z;"
"layout(location=7)uniform sampler2D A;"
"layout(location=9)uniform samplerCube y;"
"in vec3 f;"
"in vec2 t;"
"in vec2 e;"
"in vec2 n;"
"in vec2 s;"
"in vec2 u;"
"in vec2 m;"
"out vec4 o;"
"void main()"
"{"
"vec3 l=normalize(f);"
"vec4 v;"
"float c=1;"
"if(d[4].s<6000.)"
"{"
"c=ceil(mix(14.,3.,d[4].s/6000.));"
"float e=mix(t.s,t.t,.5);"
"v=vec4(texture(y,floor(f/e/c)*c*e).stp*.5,1.);"
"}"
"else v=vec4(texture(y,l).stp*.5,1.);"
"vec2 f=floor(e/t/c)*c*t,r=floor(n/t/c)*c*t,n=floor(s/t/c)*c*t,s=floor(u/t/c)*c*t,i=floor(m/t/c)*c*t;"
"vec4 a=W(z,t,f,r,n,s,i),u=min(G0(z,vec2(.005,.005),e)*.03,vec4(1));"
"float m=max(1-abs(d[4].s-21000.)/4000.,.0);"
"a.stp+=mix(vec3(0),u.stp,m),o=(1.-a.q)*v+a;"
"float t=smoothstep(-.01,.0,-abs(e.s-d[4].p));"
"if(t>0)o-=t*mod(int(t*8.),2);"
"}"
#endif
"";
