// autogenerated from src/gui/testsong.json
// Sat Jul 28 17:07:06 2018

#ifndef _SYNTH_H
#define _SYNTH_H

/* Number of float (32 bit) samples synth can safely generate without
   internal overflow, i.e. max safe value for 2nd arg of synth().
   That arg divided by 2 is the number of interleaved stereo frames generated. */

#define SONG_FRAMES (48 * 8200 * 38)

#ifdef __cplusplus
extern "C" {
#endif

__attribute__((regparm(2))) void synth(float *outbuf, int samples);

#ifdef __cplusplus
}
#endif

#endif /* _SYNTH_H */
